### ISSUE TITLE
Build review section for events

### ISSUE THREAD

**Issue by jwunderl** [jwunderl/pxt-arcade#100]
After events section is stable, for each lesson in section, build a 'review / practice' section.

This includes (at minimum)
* 2 trivial tasks (take a task or example from the lesson, make a trivial change, guide them through it)
* 1 medium level task (similar to above, except a bit more abstract / less explicit guidance)
* 1 challenge task (harder is fine, maybe something for a teacher to assign a student who is bored / already learned material)

Naming conventions: append -problems.ts to section name (e.g. types-problems)

In PR, include ``ref #100`` in the comment to include a link to the pr in this issue

## Sections

* [ ] intro -- in progress @ChaseMor 
* [ ] update -- in progress @ChaseMor 
* [ ] overlap -- in progress @ChaseMor 
* [ ] info -- in progress @ChaseMor 
* [ ] buttons -- in progress @ChaseMor

**Comment by jwunderl** [comment]
@ChaseMor can these be done by Thursday? This and the last few sections of case study additions will be the last few content additions before the course is 'content complete' for now.

**Comment by ChaseMor** [comment]
Probably not Thursday, but I can have it by the end of the week. I'm pretty swamped with stuff at the moment.
