### ISSUE TITLE
Push Orientation Files

### ISSUE THREAD

**Issue by eric-camplin** [jwunderl/pxt-arcade#14]
Cleanse the Orientation files and push live 

After https://github.com/jwunderl/pxt-arcade/issues/13 is completed and variables folder removed and topics dispersed  

Note: the Motion and Events should be good and we will work on those next

**Comment by jwunderl** [comment]
the "updateunit1" branch now contains the items I'll be including in the PR, reviewing it now.

**Comment by jwunderl** [comment]
Reviewed all material / ready to push
