### ISSUE TITLE
combine loops and events - add additonal content

### ISSUE THREAD

**Issue by eric-camplin** [jwunderl/pxt-arcade#18]
put everything together in loops 

evaluate if an additional topic or two is needed.  Collect projects that can be assigned at the end of this section.

**Comment by jwunderl** [comment]
refactored into loops-and-functions in recent commit; leaving open for now as reminder to fill out content for this section

**Comment by jwunderl** [comment]
Loops and functions now separated again, as we've changed to include jwunderl/pxt-corgio lesson in functions as lesson number 3
