### ISSUE TITLE
Create Projects assgnment for Functions

### ISSUE THREAD

**Issue by eric-camplin** [jwunderl/pxt-arcade#40]
see the projects.md for Motion & Events as well as Loops and follow the format requiring the use of 10 + items from a a list and requiring the use of at least x (2 or 3?) functions

Build sample games and create animated gif's (or assign that to Joey)

**Comment by eric-camplin** [comment]
note: Joey is creating the files and navigation https://github.com/jwunderl/pxt-arcade/issues/39

**Comment by jwunderl** [comment]
(files now exist, they're just empty. Whenever you need a gif just ping me using @jwunderl )
