### ISSUE TITLE
Logic Project

### ISSUE THREAD

**Issue by eric-camplin** [jwunderl/pxt-arcade#56]
a sprite power up game perhaps - if you have (score, lives, time) then increase (score per action, projectiles per shot, velocity in navigation)

also use the list of include N or more of the items from the list

@jwunderl  you can assign to @ChaseMor if needed

**Comment by jwunderl** [comment]
@ChaseMor I'll probably make one more, if you can think of a challenge game for logic/project go ahead and make it?
