### ISSUE TITLE
incorporate approprate review after motion & events section

### ISSUE THREAD

**Issue by eric-camplin** [jwunderl/pxt-arcade#8]
Build a review activities section following motion & events section.  Make sure that it contains items covered in the early lessons - variables, sprites, motion, overlap, projectiles, "spawning" objects

**Comment by eric-camplin** [comment]
I think this is done :) just saw summary

**Comment by jwunderl** [comment]
Yup, I added this in already ~ the first three parts are the more focused review, with further 'practice sections' we had worked on earlier as needed
