### ISSUE TITLE
 add a lesson on info methods using points, life and countdown timer.

### ISSUE THREAD

**Issue by eric-camplin** [jwunderl/pxt-arcade#9]
add a lesson on **info methods** using - score/points, life and countdown timer

Question: where is best place?  After variable math so students use math in game setting?

**Comment by jwunderl** [comment]
I'll write this up, adding in after variable math (seems to fit as a "you can interact with other variables as well" sort of follow up)

**Comment by jwunderl** [comment]
the base of the variables/info section is written out, but needs review / rubric items
